In [1]:
import numpy as np


In [2]:
myarr=np.array([12,323,435,45667,576],np.int32)
myarr

array([   12,   323,   435, 45667,   576])

In [3]:
myarr[0]

12

In [4]:
myarr2=np.array([[1,2,34,45,56,56,6,66]])
myarr2[0,1] #*for 2d array


2

In [5]:
myarr2.shape # to get information about the size of array

(1, 8)

In [6]:
myarr2.dtype

dtype('int32')

myarr[0,1]=45
mrarr
 

In [7]:
myarr2[0,1]=45 #to change the value at certain point of the array
myarr2

array([[ 1, 45, 34, 45, 56, 56,  6, 66]])

In [8]:
zeros=np.zeros((10,15)) #it would ceate an array of 10 rows and 15 column with 0 values in it

In [9]:
zeros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [10]:
a=np.arange(15) #creates array list from 0-14

In [11]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
lspace=np.linspace(1,5,12)

In [13]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [14]:
arr2=np.arange(99)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [15]:
arr2.reshape(3,33) # here number can be arranged in a set that ech set has same number of elements each (3,33)i.e
#3*33=99,here (3,31)would  give erroe bcoz 3*31=93


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [16]:
emp=np.empty((4,6))
emp#it would create an empty array with random elements

array([[3.56043053e-307, 1.60219306e-306, 7.56571288e-307,
        1.89146896e-307, 1.37961302e-306, 1.05699242e-307],
       [8.01097889e-307, 1.78020169e-306, 7.56601165e-307,
        1.02359984e-306, 1.33510679e-306, 2.22522597e-306],
       [1.33511018e-306, 6.23057689e-307, 1.33511290e-306,
        1.78019082e-306, 8.45559303e-307, 8.06613040e-308],
       [6.89810244e-307, 1.22387550e-307, 2.22522596e-306,
        8.34423917e-308, 9.79107193e-307, 1.78005909e-306]])

In [17]:
emp_like=np.empty_like(arr2)
emp_like #it would same array as size of arr2 but with random elements

array([         -1,  2147483647,           1,           0,         448,
                 0,           1,           0,         712,           0,
               411,           0,         832,           0,         411,
       -2147483392,         724,           0,         411,           0,
               872,           0,         411,           0,         792,
                 0,         411,           0,        1080,           0,
               411, -2147483136,        1084,           0,         411,
                 0,         820,           0,         411,           0,
              1044,           0,         411,           0,        1108,
                 0,         411, -2147482880,        1076,           0,
               411,           0,           0,           0,           0,
                 0,           0,           0,           0,           0,
                 0,           0, -1211391175, -2147482624,           0,
                 0,           0,           0,           0,      

In [18]:
ide=np.identity(10)
ide #it would create a indentity matrix of 10,10

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [19]:
ide.shape

(10, 10)

In [20]:
x=[[1,2,3], [4,5,6], [7,1,0]]

In [21]:
ar=np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [22]:
ar.sum(axis=0)# here we will get the sum of axis 0 of all i.e 1+4+7=12,2+5+1=8,3+6+0=9

array([12,  8,  9])

In [23]:
ar.sum(axis=1)# here we will get the sum of axis 1 of all i.e 1+2+3=6,4+5+6=15,7+1+0=8

array([ 6, 15,  8])

In [24]:
ar.T#it will transpose my array

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [25]:
ar.flat #it would give an iterator to my array

In [26]:
for item in ar.flat:
    print(item)#it would print letter individually all element of my array

1
2
3
4
5
6
7
1
0


In [27]:
ar.ndim#it would show me number dimeansion in which my array is present

2

In [28]:
ar.size

9

In [29]:
ar.nbytes

36

In [30]:
one=np.array([1,2,33454354,464576757,57867766786786,89678,6457,23])
one.argmax()#here it would give me the index of largest element in the list


4

In [31]:
one.argmin()#here it would give me the index of smallest element in the list

0

In [32]:
one.argsort()#it would give me the order of indexes in which the element would have been present then they would have been sorted 

array([0, 1, 7, 6, 5, 2, 3, 4], dtype=int64)

In [33]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [34]:
ar.argmax()#here it would give the index of largest element

6

In [35]:
ar.argmin()#it would give the index of smallest element 

8

In [36]:
ar.argmax(axis=0)#here it would give the index of largest element on axis 0

array([2, 1, 1], dtype=int64)

In [37]:
ar.argmin(axis=0)#here it would give the index of smallest element on axis=0

array([0, 2, 2], dtype=int64)

In [38]:
ar.argmin(axis=1)#here it would give the index of smallest element on axis 1

array([0, 0, 2], dtype=int64)

In [39]:
ar.argmax(axis=1)#here it would give the index of largest element on axis 1

array([2, 2, 0], dtype=int64)

In [40]:
ar.argsort(axis=0)#it would give me the order of indexes in which the element would have been present then they would have been sorted on axis 0

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [41]:
ar.argsort(axis=1)#it would give me the order of indexes in which the element would have been present then they would have been sorted on axis 1

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [42]:
ar2=np.array([[3,2,1],[6,5,3],[3,4,6]])
ar2

array([[3, 2, 1],
       [6, 5, 3],
       [3, 4, 6]])

In [43]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [44]:
ar+ar2#sum of matrix ar and ar2

array([[ 4,  4,  4],
       [10, 10,  9],
       [10,  5,  6]])

In [45]:
ar*ar2#multiplcaton of matrix ar and ar2

array([[ 3,  4,  3],
       [24, 25, 18],
       [21,  4,  0]])

In [46]:
ar/ar2#division of matrix ar and ar2

array([[0.33333333, 1.        , 3.        ],
       [0.66666667, 1.        , 2.        ],
       [2.33333333, 0.25      , 0.        ]])

In [47]:
ar-ar2#subtraction of matrix ar and ar2

array([[-2,  0,  2],
       [-2,  0,  3],
       [ 4, -3, -6]])

In [48]:
ar%ar2#modulas of matrix ar and ar2

array([[1, 0, 0],
       [4, 0, 0],
       [1, 1, 0]], dtype=int32)

In [49]:
np.sqrt(ar)#it would give us the square root of elements present in ar

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [50]:
ar.min()

0

In [51]:
ar.max()

7

In [52]:
ar.sum()

29

In [53]:
np.where(ar>5)#it would give me indexes of elements which are greater than 5

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [56]:
np.count_nonzero(ar)  #it would give me the count of number of element which are in non 0 form

8

In [57]:
np.nonzero(ar)  #it would give me the tuple form  of number of element which are in non 0 form

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [58]:
ar[1,2]=0

In [61]:
np.nonzero(ar)  #it would give me the count of number of element which are in non 0 form

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

In [62]:
import sys


In [63]:
py_ar=[0,2,3,4,5,6]

In [64]:
np_ar=np.array(py_ar)

In [67]:
sys.getsizeof(1)*len(py_ar)

168

In [69]:
np_ar.itemsize*np_ar.size

24